# Generated by Django 5.1 on 2025-08-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'HR Manager'), ('Staff', 'Staff')], max_length=20)),
                ('maiden_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('directorate', models.CharField(max_length=20)),
                ('current_grade', models.CharField(max_length=20)),
                ('next_grade', models.CharField(max_length=20)),
                ('current_salary_level', models.CharField(max_length=20)),
                ('current_salary_point', models.CharField(max_length=20)),
                ('next_salary_level', models.CharField(max_length=20)),
                ('date_of_first_appointment', models.DateField()),
                ('date_of_assumption_of_duty', models.DateField()),
                ('date_of_last_promotion', models.DateField()),
                ('change_of_grade', models.CharField(max_length=20)),
                ('substantive_date', models.DateField()),
                ('national_effective_date', models.DateField()),
                ('years_on_current_grade', models.IntegerField()),
                ('number_of_years_in_service', models.IntegerField()),
                ('fulltime_contract_staff', models.CharField(max_length=20)),
                ('academic_qualification', models.CharField(max_length=20)),
                ('professional_qualification', models.CharField(max_length=20)),
                ('staff_category', models.CharField(choices=[('senior_staff', 'SENIOR STAFF'), ('junior_staff', 'JUNIOR STAFF')], max_length=20)),
                ('region', models.CharField(choices=[('AHAFO', 'AHAFO'), ('ASHANTI', 'ASHANTI'), ('BONO & BONO EAST', 'BONO & BONO EAST'), ('CENTRAL', 'CENTRAL'), ('EASTERN', 'EASTERN'), ('GREATER ACCRA', 'GREATER ACCRA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('NORTHERN', 'NORTHERN'), ('UPPER EAST', 'UPPER EAST'), ('WESTERN', 'WESTERN'), ('WESTERN NORTH', 'WESTERN NORTH')], max_length=20)),
                ('district', models.CharField(choices=[('Accra Metropolitan Assembly', 'Accra Metropolitan Assembly'), ('Asunafo North', 'Asunafo North'), ('Sekondi-Takoradi Metropolitan Assembly', 'Sekondi-Takoradi Metropolitan Assembly'), ('Sekondi', 'Sekondi'), ('Techiman', 'Techiman'), ('Mfantseman Municipal Assembly', 'Mfantseman Municipal Assembly'), ('Head Office', 'Head Office'), ('Sunyani Municipal', 'Sunyani Municipal'), ('Berekum', 'Berekum'), ('Tano North Municipal', 'Tano North Municipal'), ('Regional Office', 'Regional Office'), ('Asuogyaman District Assembly', 'Asuogyaman District Assembly'), ('Kade District', 'Kade District'), ('Nkoranza North & South', 'Nkoranza North & South'), ('Aowin', 'Aowin'), ('Abuakwa North Municipal', 'Abuakwa North Municipal'), ('Kwahu West', 'Kwahu West'), ('Kwahu', 'Kwahu'), ('Yeji Pru East', 'Yeji Pru East'), ('Aowin Municipal', 'Aowin Municipal'), ('Birim North District', 'Birim North District'), ('Kwahu Afram Plains South', 'Kwahu Afram Plains South'), ('Asuogyaman', 'Asuogyaman'), ('Akim Oda', 'Akim Oda'), ('Asamankese', 'Asamankese'), ('New Juaben South', 'New Juaben South'), ('Kwaebibirem Municipality', 'Kwaebibirem Municipality'), ('Birim South District', 'Birim South District'), ('Atiwa East', 'Atiwa East'), ('West Akim Municipal', 'West Akim Municipal'), ('New Abirem', 'New Abirem'), ('New Tafo-Akyem (Abuakwa North Municipal Assembly)', 'New Tafo-Akyem (Abuakwa North Municipal Assembly)'), ('Sunyani Municipal Assembly', 'Sunyani Municipal Assembly'), ('Asene Manso Akroso', 'Asene Manso Akroso'), ('Fanteakwa North District Assembly', 'Fanteakwa North District Assembly'), ('New Juaben North', 'New Juaben North'), ('Sunyani', 'Sunyani'), ('Sunyani Municipality', 'Sunyani Municipality'), ('Jaman South Municipal', 'Jaman South Municipal'), ('Bia West', 'Bia West'), ('Wenchi', 'Wenchi'), ('Dormaa West', 'Dormaa West'), ('Begoro', 'Begoro'), ('Banda District', 'Banda District'), ('Kyebi', 'Kyebi'), ('La Dadekotopone', 'La Dadekotopone'), ('Dambai', 'Dambai'), ('Assin Foso', 'Assin Foso'), ('Techiman North', 'Techiman North'), ('Sefwi Wiawso Municipal', 'Sefwi Wiawso Municipal'), ('La Dade Kotopong', 'La Dade Kotopong'), ('Asutifi North', 'Asutifi North'), ('Kumasi Metropolitan Assembly', 'Kumasi Metropolitan Assembly'), ('Bolgatanga Municipal', 'Bolgatanga Municipal'), ('Weija Gbawe', 'Weija Gbawe'), ('Jaman North', 'Jaman North'), ('Elubo', 'Elubo'), ('Kwabiberium Municipal Assembly', 'Kwabiberium Municipal Assembly'), ('Dormaa Municipal', 'Dormaa Municipal'), ('Tarkwa Nsuaem', 'Tarkwa Nsuaem'), ('Akyemansa', 'Akyemansa'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Asankragwa', 'Asankragwa'), ('Sefwi Bodi', 'Sefwi Bodi'), ('Daboase', 'Daboase'), ('Axim', 'Axim'), ('Nkwanta - South', 'Nkwanta - South'), ('Shai Osu-Doku District', 'Shai Osu-Doku District'), ('Bosomtwe District', 'Bosomtwe District'), ('Antwima Mponua', 'Antwima Mponua'), ('Wassa East', 'Wassa East'), ('Kasoa', 'Kasoa'), ('Ga Central Municipality', 'Ga Central Municipality'), ('Bole', 'Bole'), ('Twifo Atti-Morkwa', 'Twifo Atti-Morkwa'), ('Obuasi', 'Obuasi'), ('Madina Municipal Branch Office', 'Madina Municipal Branch Office'), ('Builsa North Municipal', 'Builsa North Municipal'), ('Amansie West', 'Amansie West'), ('Madina Municipal', 'Madina Municipal'), ('Offinso', 'Offinso'), ('Sekondi-Takoradi', 'Sekondi-Takoradi'), ('Twifo Praso', 'Twifo Praso'), ('Bia East', 'Bia East'), ('Bibiani Anhwiaso Bekwai', 'Bibiani Anhwiaso Bekwai'), ('Ledzekuku-Krowor', 'Ledzekuku-Krowor'), ('West Mamprusi', 'West Mamprusi'), ('Teshie-Nungua', 'Teshie-Nungua'), ('Salaga', 'Salaga'), ('Atwima Mponua', 'Atwima Mponua'), ('Bawku Municipal', 'Bawku Municipal'), ('Juaboso', 'Juaboso'), ('Bibiani', 'Bibiani'), ('Atwima Nwabiagya North', 'Atwima Nwabiagya North'), ('Bibiani, Awheaso, Bekwai', 'Bibiani, Awheaso, Bekwai'), ('Kassena Nankana West', 'Kassena Nankana West'), ('Techiman Municipal', 'Techiman Municipal'), ('Konongo', 'Konongo'), ('Afigya Kwabre South District', 'Afigya Kwabre South District'), ('Kasoa Sub-Region', 'Kasoa Sub-Region'), ('Secondi Takoradi', 'Secondi Takoradi'), ('Jomoro', 'Jomoro'), ('Assin Foso', 'Assin Foso'), ('Prestea-Huni Valley', 'Prestea-Huni Valley'), ('Adansi South District', 'Adansi South District'), ('Madina District', 'Madina District'), ('Wassa Akropong', 'Wassa Akropong'), ('Kwabre East Municipal', 'Kwabre East Municipal'), ('Osu Klottey', 'Osu Klottey'), ('Tano South', 'Tano South'), ('Asante Mampong Municipality', 'Asante Mampong Municipality'), ('Sekyere South', 'Sekyere South'), ('Atwima Kwanwoma District', 'Atwima Kwanwoma District'), ('Suaman', 'Suaman'), ('Ahafo Ano North', 'Ahafo Ano North'), ('Agona Swedru', 'Agona Swedru'), ('Asunafo North Municipal Assembly', 'Asunafo North Municipal Assembly'), ('Awutu Senya West', 'Awutu Senya West'), ('Nkawie', 'Nkawie'), ('Asunafo South', 'Asunafo South'), ('Adansi South', 'Adansi South'), ('Sekyere-East District', 'Sekyere-East District'), ('Nzema East Municipal', 'Nzema East Municipal'), ('Asutifi South', 'Asutifi South'), ('Asikuma Odoben Brakwa', 'Asikuma Odoben Brakwa'), ('Awutu Senya East Municipal Assembly', 'Awutu Senya East Municipal Assembly'), ('Asokore Mampong', 'Asokore Mampong'), ('Ejisu Municipal', 'Ejisu Municipal'), ('Suame', 'Suame'), ('Ejura-Sekyedumase', 'Ejura-Sekyedumase'), ('Prampram', 'Prampram'), ('Offinso North District', 'Offinso North District'), ('Ahafo Ano South', 'Ahafo Ano South'), ('Sekyere Kumawu', 'Sekyere Kumawu'), ('Sefwi Wiawso Municipal Assembly', 'Sefwi Wiawso Municipal Assembly'), ('Game North', 'Game North'), ('Dunkwa-On-Offin', 'Dunkwa-On-Offin'), ('Sunyani East Municipality', 'Sunyani East Municipality'), ('Dormaa Central', 'Dormaa Central'), ('Kintampo South', 'Kintampo South'), ('Atebubu', 'Atebubu'), ('Kintampo North', 'Kintampo North')], max_length=100, verbose_name='District')),
                ('single_spine_monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_retirement', models.DateField()),
                ('number_of_focus_areas', models.IntegerField()),
                ('number_of_targets', models.IntegerField()),
                ('number_of_targets_met', models.IntegerField()),
                ('number_of_targets_not_met', models.IntegerField()),
                ('overall_assessment_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('self_assessment_description', models.TextField()),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('ghana_card_number', models.CharField(max_length=20, unique=True)),
                ('social_security_number', models.CharField(max_length=20, unique=True)),
                ('national_health_insurance_number', models.CharField(max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=50, unique=True)),
                ('bank_account_branch', models.CharField(max_length=50)),
                ('management_unit_cost_centre', models.CharField(max_length=100)),
                ('payroll_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], max_length=50)),
                ('at_post_on_leave', models.CharField(choices=[('At Post', 'At Post'), ('On Leave', 'On Leave')], max_length=20)),
                ('on_leave_type', models.CharField(blank=True, max_length=50, null=True)),
                ('accommodation_status', models.CharField(choices=[('Company Accommodation', 'Company Accommodation'), ('Personal Residence', 'Personal Residence'), ('Rented Residence', 'Rented Residence')], max_length=50)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
