# Generated by Django 5.1 on 2025-08-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='accommodation_status',
            field=models.CharField(blank=True, choices=[('Company Accommodation', 'Company Accommodation'), ('Personal Residence', 'Personal Residence'), ('Rented Residence', 'Rented Residence')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='at_post_on_leave',
            field=models.CharField(blank=True, choices=[('At Post', 'At Post'), ('On Leave', 'On Leave')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('Accounts Class', 'Accounts Class'), ('Administrative Class', 'Administrative Class'), ('Audit Class', 'Audit Class'), ('Drivers Class', 'Drivers Class'), ('Executive Class', 'Executive Class'), ('Information Class', 'Information Class'), ('Information Technology Class', 'Information Technology Class'), ('Labourers Class', 'Labourers Class'), ('Procurement Class', 'Procurement Class'), ('Programme Class', 'Programme Class'), ('Records Class', 'Records Class'), ('Revenue Class', 'Revenue Class'), ('Revenue Inspector Class', 'Revenue Inspector Class'), ('Sanitation Class', 'Sanitation Class'), ('Secretarial Class', 'Secretarial Class'), ('Security Class', 'Security Class'), ('Stool Lands Class', 'Stool Lands Class'), ('Stool Lands Inspectors Class', 'Stool Lands Inspectors Class'), ('Stool Lands Revenue Class', 'Stool Lands Revenue Class')], max_length=100, null=True, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='change_of_grade',
            field=models.CharField(blank=True, choices=[('First Appointment', 'First Appointment'), ('High Academic Qualification', 'High Academic Qualification'), ('Letter Of Appointment', 'Letter Of Appointment'), ('None', 'None'), ('Promotion', 'Promotion'), ('Regrading (Conversion/Upgrading)', 'Regrading (Conversion/Upgrading)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_grade',
            field=models.CharField(blank=True, choices=[('Accountant', 'Accountant'), ('Administrator Of Stool Lands', 'Administrator Of Stool Lands'), ('Assistant Accountant', 'Assistant Accountant'), ('Assistant Chief Executive Officer', 'Assistant Chief Executive Officer'), ('Assistant Chief Stool Lands Inspector', 'Assistant Chief Stool Lands Inspector'), ('Assistant Director IIA', 'Assistant Director IIA'), ('Assistant Director IIB', 'Assistant Director IIB'), ('Assistant Information Officer', 'Assistant Information Officer'), ('Assistant Internal Auditor', 'Assistant Internal Auditor'), ('Assistant Procurement & Supply Chain Manager', 'Assistant Procurement & Supply Chain Manager'), ('Assistant Stool Lands Officer', 'Assistant Stool Lands Officer'), ('Chief Accountant', 'Chief Accountant'), ('Chief Executive Officer', 'Chief Executive Officer'), ('Chief Headman', 'Chief Headman'), ('Chief Headman Labourer', 'Chief Headman Labourer'), ('Chief Revenue Superintendent', 'Chief Revenue Superintendent'), ('Chief Stool Lands Inspector', 'Chief Stool Lands Inspector'), ('Chief Stool Lands Officer', 'Chief Stool Lands Officer'), ('Deputy Chief Stool Lands Inspector', 'Deputy Chief Stool Lands Inspector'), ('Deputy Chief Stool Lands Officer', 'Deputy Chief Stool Lands Officer'), ('Deputy Director', 'Deputy Director'), ('Deputy Stool Lands Inspector', 'Deputy Stool Lands Inspector'), ('Deputy Stool Lands Officer', 'Deputy Stool Lands Officer'), ('Driver Grade I', 'Driver Grade I'), ('Driver Grade II', 'Driver Grade II'), ('Driver Grade III', 'Driver Grade III'), ('Executive Officer', 'Executive Officer'), ('Headman', 'Headman'), ('Heavy Duty', 'Heavy Duty'), ('Higher Executive Officer', 'Higher Executive Officer'), ('Higher Revenue Inspector', 'Higher Revenue Inspector'), ('Internal Auditor', 'Internal Auditor'), ('IT/IM Officer', 'IT/IM Officer'), ('Principal Account Technician', 'Principal Account Technician'), ('Principal Accountant', 'Principal Accountant'), ('Principal Executive Officer', 'Principal Executive Officer'), ('Principal Procurement & Supply Chain Manager', 'Principal Procurement & Supply Chain Manager'), ('Principal Revenue Superintendent', 'Principal Revenue Superintendent'), ('Principal Stool Lands Inspector', 'Principal Stool Lands Inspector'), ('Principal Stool Lands Officer', 'Principal Stool Lands Officer'), ('Private Secretary', 'Private Secretary'), ('Procurement & Supply Chain Officer', 'Procurement & Supply Chain Officer'), ('Programme Officer', 'Programme Officer'), ('Records Officer', 'Records Officer'), ('Revenue', 'Revenue'), ('Revenue Collector', 'Revenue Collector'), ('Revenue Inspector', 'Revenue Inspector'), ('Revenue Superintendent', 'Revenue Superintendent'), ('Sanitary Labourer', 'Sanitary Labourer'), ('Senior Accountant', 'Senior Accountant'), ('Senior Executive Officer', 'Senior Executive Officer'), ('Senior Private Secretary', 'Senior Private Secretary'), ('Senior Records Officer', 'Senior Records Officer'), ('Senior Revenue Superintendent', 'Senior Revenue Superintendent'), ('Senior Stool Lands Officer', 'Senior Stool Lands Officer'), ('Ss11', 'Ss11'), ('Stenographer Grade I', 'Stenographer Grade I'), ('Stenographer Grade II', 'Stenographer Grade II'), ('Stenographer Secretary', 'Stenographer Secretary'), ('Stool Lands Inspector', 'Stool Lands Inspector'), ('Stool Lands Officer', 'Stool Lands Officer'), ('Watchman Night', 'Watchman Night'), ('Yard Foreman', 'Yard Foreman')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_salary_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_salary_point',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_assumption_of_duty',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_first_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_last_promotion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_retirement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='directorate',
            field=models.CharField(blank=True, choices=[('Administration & Human Resource Directorate - ICT Unit', 'Administration & Human Resource Directorate - ICT Unit'), ('Administration & Human Resource Directorate - Information Unit & Public Relations Unit', 'Administration & Human Resource Directorate - Information Unit & Public Relations Unit'), ('Administration & Human Resource Directorate - Procurement Unit', 'Administration & Human Resource Directorate - Procurement Unit'), ('Administration & Human Resource Directorate - Records', 'Administration & Human Resource Directorate - Records'), ('Administration & Human Resource Directorate - Transport Unit', 'Administration & Human Resource Directorate - Transport Unit'), ('Audit Unit', 'Audit Unit'), ('Finance Directorate', 'Finance Directorate'), ('General Administration & Human Resource Directorate', 'General Administration & Human Resource Directorate'), ('Land Administration Directorate', 'Land Administration Directorate'), ('Legal Unit', 'Legal Unit'), ('Operations Directorate', 'Operations Directorate'), ('Policy Planning Directorate', 'Policy Planning Directorate'), ('Research Statistics & Information Management Directorate', 'Research Statistics & Information Management Directorate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('Accra Metropolitan Assembly', 'Accra Metropolitan Assembly'), ('Asunafo North', 'Asunafo North'), ('Sekondi-Takoradi Metropolitan Assembly', 'Sekondi-Takoradi Metropolitan Assembly'), ('Sekondi', 'Sekondi'), ('Techiman', 'Techiman'), ('Mfantseman Municipal Assembly', 'Mfantseman Municipal Assembly'), ('Head Office', 'Head Office'), ('Sunyani Municipal', 'Sunyani Municipal'), ('Berekum', 'Berekum'), ('Tano North Municipal', 'Tano North Municipal'), ('Regional Office', 'Regional Office'), ('Asuogyaman District Assembly', 'Asuogyaman District Assembly'), ('Kade District', 'Kade District'), ('Nkoranza North & South', 'Nkoranza North & South'), ('Aowin', 'Aowin'), ('Abuakwa North Municipal', 'Abuakwa North Municipal'), ('Kwahu West', 'Kwahu West'), ('Kwahu', 'Kwahu'), ('Yeji Pru East', 'Yeji Pru East'), ('Aowin Municipal', 'Aowin Municipal'), ('Birim North District', 'Birim North District'), ('Kwahu Afram Plains South', 'Kwahu Afram Plains South'), ('Asuogyaman', 'Asuogyaman'), ('Akim Oda', 'Akim Oda'), ('Asamankese', 'Asamankese'), ('New Juaben South', 'New Juaben South'), ('Kwaebibirem Municipality', 'Kwaebibirem Municipality'), ('Birim South District', 'Birim South District'), ('Atiwa East', 'Atiwa East'), ('West Akim Municipal', 'West Akim Municipal'), ('New Abirem', 'New Abirem'), ('New Tafo-Akyem (Abuakwa North Municipal Assembly)', 'New Tafo-Akyem (Abuakwa North Municipal Assembly)'), ('Sunyani Municipal Assembly', 'Sunyani Municipal Assembly'), ('Asene Manso Akroso', 'Asene Manso Akroso'), ('Fanteakwa North District Assembly', 'Fanteakwa North District Assembly'), ('New Juaben North', 'New Juaben North'), ('Sunyani', 'Sunyani'), ('Sunyani Municipality', 'Sunyani Municipality'), ('Jaman South Municipal', 'Jaman South Municipal'), ('Bia West', 'Bia West'), ('Wenchi', 'Wenchi'), ('Dormaa West', 'Dormaa West'), ('Begoro', 'Begoro'), ('Banda District', 'Banda District'), ('Kyebi', 'Kyebi'), ('La Dadekotopone', 'La Dadekotopone'), ('Dambai', 'Dambai'), ('Assin Foso', 'Assin Foso'), ('Techiman North', 'Techiman North'), ('Sefwi Wiawso Municipal', 'Sefwi Wiawso Municipal'), ('La Dade Kotopong', 'La Dade Kotopong'), ('Asutifi North', 'Asutifi North'), ('Kumasi Metropolitan Assembly', 'Kumasi Metropolitan Assembly'), ('Bolgatanga Municipal', 'Bolgatanga Municipal'), ('Weija Gbawe', 'Weija Gbawe'), ('Jaman North', 'Jaman North'), ('Elubo', 'Elubo'), ('Kwabiberium Municipal Assembly', 'Kwabiberium Municipal Assembly'), ('Dormaa Municipal', 'Dormaa Municipal'), ('Tarkwa Nsuaem', 'Tarkwa Nsuaem'), ('Akyemansa', 'Akyemansa'), ('Kumasi', 'Kumasi'), ('Cape Coast', 'Cape Coast'), ('Asankragwa', 'Asankragwa'), ('Sefwi Bodi', 'Sefwi Bodi'), ('Daboase', 'Daboase'), ('Axim', 'Axim'), ('Nkwanta - South', 'Nkwanta - South'), ('Shai Osu-Doku District', 'Shai Osu-Doku District'), ('Bosomtwe District', 'Bosomtwe District'), ('Antwima Mponua', 'Antwima Mponua'), ('Wassa East', 'Wassa East'), ('Kasoa', 'Kasoa'), ('Ga Central Municipality', 'Ga Central Municipality'), ('Bole', 'Bole'), ('Twifo Atti-Morkwa', 'Twifo Atti-Morkwa'), ('Obuasi', 'Obuasi'), ('Madina Municipal Branch Office', 'Madina Municipal Branch Office'), ('Builsa North Municipal', 'Builsa North Municipal'), ('Amansie West', 'Amansie West'), ('Madina Municipal', 'Madina Municipal'), ('Offinso', 'Offinso'), ('Sekondi-Takoradi', 'Sekondi-Takoradi'), ('Twifo Praso', 'Twifo Praso'), ('Bia East', 'Bia East'), ('Bibiani Anhwiaso Bekwai', 'Bibiani Anhwiaso Bekwai'), ('Ledzekuku-Krowor', 'Ledzekuku-Krowor'), ('West Mamprusi', 'West Mamprusi'), ('Teshie-Nungua', 'Teshie-Nungua'), ('Salaga', 'Salaga'), ('Atwima Mponua', 'Atwima Mponua'), ('Bawku Municipal', 'Bawku Municipal'), ('Juaboso', 'Juaboso'), ('Bibiani', 'Bibiani'), ('Atwima Nwabiagya North', 'Atwima Nwabiagya North'), ('Bibiani, Awheaso, Bekwai', 'Bibiani, Awheaso, Bekwai'), ('Kassena Nankana West', 'Kassena Nankana West'), ('Techiman Municipal', 'Techiman Municipal'), ('Konongo', 'Konongo'), ('Afigya Kwabre South District', 'Afigya Kwabre South District'), ('Kasoa Sub-Region', 'Kasoa Sub-Region'), ('Secondi Takoradi', 'Secondi Takoradi'), ('Jomoro', 'Jomoro'), ('Assin Foso', 'Assin Foso'), ('Prestea-Huni Valley', 'Prestea-Huni Valley'), ('Adansi South District', 'Adansi South District'), ('Madina District', 'Madina District'), ('Wassa Akropong', 'Wassa Akropong'), ('Kwabre East Municipal', 'Kwabre East Municipal'), ('Osu Klottey', 'Osu Klottey'), ('Tano South', 'Tano South'), ('Asante Mampong Municipality', 'Asante Mampong Municipality'), ('Sekyere South', 'Sekyere South'), ('Atwima Kwanwoma District', 'Atwima Kwanwoma District'), ('Suaman', 'Suaman'), ('Ahafo Ano North', 'Ahafo Ano North'), ('Agona Swedru', 'Agona Swedru'), ('Asunafo North Municipal Assembly', 'Asunafo North Municipal Assembly'), ('Awutu Senya West', 'Awutu Senya West'), ('Nkawie', 'Nkawie'), ('Asunafo South', 'Asunafo South'), ('Adansi South', 'Adansi South'), ('Sekyere-East District', 'Sekyere-East District'), ('Nzema East Municipal', 'Nzema East Municipal'), ('Asutifi South', 'Asutifi South'), ('Asikuma Odoben Brakwa', 'Asikuma Odoben Brakwa'), ('Awutu Senya East Municipal Assembly', 'Awutu Senya East Municipal Assembly'), ('Asokore Mampong', 'Asokore Mampong'), ('Ejisu Municipal', 'Ejisu Municipal'), ('Suame', 'Suame'), ('Ejura-Sekyedumase', 'Ejura-Sekyedumase'), ('Prampram', 'Prampram'), ('Offinso North District', 'Offinso North District'), ('Ahafo Ano South', 'Ahafo Ano South'), ('Sekyere Kumawu', 'Sekyere Kumawu'), ('Sefwi Wiawso Municipal Assembly', 'Sefwi Wiawso Municipal Assembly'), ('Game North', 'Game North'), ('Dunkwa-On-Offin', 'Dunkwa-On-Offin'), ('Sunyani East Municipality', 'Sunyani East Municipality'), ('Dormaa Central', 'Dormaa Central'), ('Kintampo South', 'Kintampo South'), ('Atebubu', 'Atebubu'), ('Kintampo North', 'Kintampo North')], max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fulltime_contract_staff',
            field=models.CharField(blank=True, choices=[('FULLTIME', 'FULLTIME'), ('CONTRACT', 'CONTRACT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='management_unit_cost_centre',
            field=models.CharField(blank=True, choices=[('0101 ASL: Office Of The Admin Of Stool Lands', '0101 ASL: Office Of The Admin Of Stool Lands'), ('0101 ASL: Admin Of Stool Lands, Accra', '0101 ASL: Admin Of Stool Lands, Accra'), ('0101 CAGD/MT Stool Lands', '0101 CAGD/MT Stool Lands'), ('0101 MLF (OASL)', '0101 MLF (OASL)'), ('0101 MOC: Info. Services Dept. Head O COST CENTER', '0101 MOC: Info. Services Dept. Head O COST CENTER'), ('0101 PG: Parks And Gardens HQ', '0101 PG: Parks And Gardens HQ'), ('0200 MOF/CAGD-Eastern Regional Directorate', '0200 MOF/CAGD-Eastern Regional Directorate'), ('0208 ASL: Admin Of Stool Lands, Koforidua', '0208 ASL: Admin Of Stool Lands, Koforidua'), ('0313 ASL: Admin Of Stool Lands, Cape Coast', '0313 ASL: Admin Of Stool Lands, Cape Coast'), ('0313 Administrator of Stool Lands', '0313 Administrator of Stool Lands'), ('0400 LGS Western Regional Coordinating Council', '0400 LGS Western Regional Coordinating Council'), ('0400 MOF/CAGD: Western Regional Directorate', '0400 MOF/CAGD: Western Regional Directorate'), ('0408 ASL: Admin Of Stool Lands, Sekondi', '0408 ASL: Admin Of Stool Lands, Sekondi'), ('0408 LGS Sekondi Takoradi Metropolitan Assembly', '0408 LGS Sekondi Takoradi Metropolitan Assembly'), ('0600 MOF/CAGD: Ashanti Regional Directorate', '0600 MOF/CAGD: Ashanti Regional Directorate'), ('0600 Regional Administration: Ashanti Regional', '0600 Regional Administration: Ashanti Regional'), ('0613 ASL: Admin Of Stool Lands, Kumasi', '0613 ASL: Admin Of Stool Lands, Kumasi'), ('0712 ASL: Admin Of Stool Lands, Sunyani', '0712 ASL: Admin Of Stool Lands, Sunyani'), ('0800 LGS: Northern Regional Coordinating Cost Centre', '0800 LGS: Northern Regional Coordinating Cost Centre'), ('0813 ASL: Admin Of Stool Lands, Accra Metropolitan Assembly', '0813 ASL: Admin Of Stool Lands, Accra Metropolitan Assembly'), ('1300 CAGD: Ahafo Regional Directorate', '1300 CAGD: Ahafo Regional Directorate'), ('310 MOF/CAGD: Central Regional Directorate', '310 MOF/CAGD: Central Regional Directorate'), ('310 MOF/CAGD: Upper Denkyira East Municipal', '310 MOF/CAGD: Upper Denkyira East Municipal'), ('Administrator of Stool Lands - Western North Region', 'Administrator of Stool Lands - Western North Region'), ('Office of the Administrator of Stool Lands - Western North Region', 'Office of the Administrator of Stool Lands - Western North Region'), ('OASL Western North Region', 'OASL Western North Region'), ('OASL District Officers Conference - Ejisu', 'OASL District Officers Conference - Ejisu')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_gross_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_health_insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_grade',
            field=models.CharField(blank=True, choices=[('Accountant', 'Accountant'), ('Administrator Of Stool Lands', 'Administrator Of Stool Lands'), ('Assistant Accountant', 'Assistant Accountant'), ('Assistant Chief Executive Officer', 'Assistant Chief Executive Officer'), ('Assistant Chief Stool Lands Inspector', 'Assistant Chief Stool Lands Inspector'), ('Assistant Director IIA', 'Assistant Director IIA'), ('Assistant Director IIB', 'Assistant Director IIB'), ('Assistant Information Officer', 'Assistant Information Officer'), ('Assistant Internal Auditor', 'Assistant Internal Auditor'), ('Assistant Procurement & Supply Chain Manager', 'Assistant Procurement & Supply Chain Manager'), ('Assistant Stool Lands Officer', 'Assistant Stool Lands Officer'), ('Chief Accountant', 'Chief Accountant'), ('Chief Executive Officer', 'Chief Executive Officer'), ('Chief Headman', 'Chief Headman'), ('Chief Headman Labourer', 'Chief Headman Labourer'), ('Chief Revenue Superintendent', 'Chief Revenue Superintendent'), ('Chief Stool Lands Inspector', 'Chief Stool Lands Inspector'), ('Chief Stool Lands Officer', 'Chief Stool Lands Officer'), ('Deputy Chief Stool Lands Inspector', 'Deputy Chief Stool Lands Inspector'), ('Deputy Chief Stool Lands Officer', 'Deputy Chief Stool Lands Officer'), ('Deputy Director', 'Deputy Director'), ('Deputy Stool Lands Inspector', 'Deputy Stool Lands Inspector'), ('Deputy Stool Lands Officer', 'Deputy Stool Lands Officer'), ('Driver Grade I', 'Driver Grade I'), ('Driver Grade II', 'Driver Grade II'), ('Driver Grade III', 'Driver Grade III'), ('Executive Officer', 'Executive Officer'), ('Headman', 'Headman'), ('Heavy Duty', 'Heavy Duty'), ('Higher Executive Officer', 'Higher Executive Officer'), ('Higher Revenue Inspector', 'Higher Revenue Inspector'), ('Internal Auditor', 'Internal Auditor'), ('IT/IM Officer', 'IT/IM Officer'), ('Principal Account Technician', 'Principal Account Technician'), ('Principal Accountant', 'Principal Accountant'), ('Principal Executive Officer', 'Principal Executive Officer'), ('Principal Procurement & Supply Chain Manager', 'Principal Procurement & Supply Chain Manager'), ('Principal Revenue Superintendent', 'Principal Revenue Superintendent'), ('Principal Stool Lands Inspector', 'Principal Stool Lands Inspector'), ('Principal Stool Lands Officer', 'Principal Stool Lands Officer'), ('Private Secretary', 'Private Secretary'), ('Procurement & Supply Chain Officer', 'Procurement & Supply Chain Officer'), ('Programme Officer', 'Programme Officer'), ('Records Officer', 'Records Officer'), ('Revenue', 'Revenue'), ('Revenue Collector', 'Revenue Collector'), ('Revenue Inspector', 'Revenue Inspector'), ('Revenue Superintendent', 'Revenue Superintendent'), ('Sanitary Labourer', 'Sanitary Labourer'), ('Senior Accountant', 'Senior Accountant'), ('Senior Executive Officer', 'Senior Executive Officer'), ('Senior Private Secretary', 'Senior Private Secretary'), ('Senior Records Officer', 'Senior Records Officer'), ('Senior Revenue Superintendent', 'Senior Revenue Superintendent'), ('Senior Stool Lands Officer', 'Senior Stool Lands Officer'), ('Ss11', 'Ss11'), ('Stenographer Grade I', 'Stenographer Grade I'), ('Stenographer Grade II', 'Stenographer Grade II'), ('Stenographer Secretary', 'Stenographer Secretary'), ('Stool Lands Inspector', 'Stool Lands Inspector'), ('Stool Lands Officer', 'Stool Lands Officer'), ('Watchman Night', 'Watchman Night'), ('Yard Foreman', 'Yard Foreman')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_salary_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_focus_areas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_targets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_targets_met',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_targets_not_met',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_years_in_service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='overall_assessment_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='payroll_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional_qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('AHAFO', 'AHAFO'), ('ASHANTI', 'ASHANTI'), ('BONO & BONO EAST', 'BONO & BONO EAST'), ('CENTRAL', 'CENTRAL'), ('EASTERN', 'EASTERN'), ('GREATER ACCRA', 'GREATER ACCRA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('NORTHERN', 'NORTHERN'), ('UPPER EAST', 'UPPER EAST'), ('WESTERN', 'WESTERN'), ('WESTERN NORTH', 'WESTERN NORTH')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_assessment_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='single_spine_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_category',
            field=models.CharField(blank=True, choices=[('senior_staff', 'SENIOR STAFF'), ('junior_staff', 'JUNIOR STAFF')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='substantive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Esq.', 'Esq.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_on_current_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
