# Generated by Django 5.1 on 2025-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_academic_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='payroll_status',
            field=models.CharField(blank=True, choices=[('ACTIVE (PAID)', 'ACTIVE (PAID)'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], max_length=50, null=True),
        ),
    ]
