# Generated by Django 5.1 on 2025-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_bank_account_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_category',
            field=models.CharField(blank=True, choices=[('SENIOR STAFF', 'SENIOR STAFF'), ('JUNIOR STAFF', 'JUNIOR STAFF')], max_length=20, null=True),
        ),
    ]
