# Generated by Django 5.1 on 2025-08-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_staff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accommodation_status',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'PERSONAL'), ('RENTED', 'RENTED'), ('OFFICIAL RESIDENCE - OASL', 'OFFICIAL RESIDENCE - OASL'), ('OFFICIAL RESIDENCE - OASL', 'OFFICIAL RESIDENCE - OASL'), ('OFFICIAL RESIDENCE - GoG', 'OFFICIAL RESIDENCE - GoG'), ('OFFICIAL RESIDENCE - GoG', 'OFFICIAL RESIDENCE - GoG')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='at_post_on_leave',
            field=models.CharField(blank=True, choices=[('AT POST', 'AT POST'), ('ON LEAVE', 'ON LEAVE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('Accra Metropolitan Assembly', 'Accra Metropolitan Assembly'), ('Akim Oda', 'Akim Oda'), ('Akim Ofoase', 'Akim Ofoase'), ('Akyemansa', 'Akyemansa'), ('Asamankese', 'Asamankese'), ('Asene Manso Akroso', 'Asene Manso Akroso'), ('Asunafo North', 'Asunafo North'), ('Asutifi North', 'Asutifi North'), ('Axim', 'Axim'), ('Begoro', 'Begoro'), ('Berekum', 'Berekum'), ('Birim North District', 'Birim North District'), ('Birim South District', 'Birim South District'), ('Bolgatanga Municipal', 'Bolgatanga Municipal'), ('Cape Coast', 'Cape Coast'), ('Daboase', 'Daboase'), ('Dormaa Municipal', 'Dormaa Municipal'), ('Dormaa West', 'Dormaa West'), ('Duayaw Nkwanta', 'Duayaw Nkwanta'), ('Ejisu', 'Ejisu'), ('Elubo', 'Elubo'), ('Enchi', 'Enchi'), ('Essikado', 'Essikado'), ('Kade District', 'Kade District'), ('Koforidua', 'Koforidua'), ('Kumasi Metropolitan Assembly', 'Kumasi Metropolitan Assembly'), ('Kumasi Metropolitan District', 'Kumasi Metropolitan District'), ('Kwahu Afram Plains South', 'Kwahu Afram Plains South'), ('Kwahu West', 'Kwahu West'), ('Kyebi', 'Kyebi'), ('La Dadekotopone', 'La Dadekotopone'), ('Mfantseman Municipal Assembly', 'Mfantseman Municipal Assembly'), ('New Juaben South Municipal', 'New Juaben South Municipal'), ('New Tafo-Akyem (Abuakwa North Municipal Assembly)', 'New Tafo-Akyem (Abuakwa North Municipal Assembly)'), ('Nkawkaw', 'Nkawkaw'), ('Nkoranza North & South', 'Nkoranza North & South'), ('Osu', 'Osu'), ('Sefwi Wiawso Municipal', 'Sefwi Wiawso Municipal'), ('Sekondi', 'Sekondi'), ('Sekondi-Takoradi Metropolitan Assembly', 'Sekondi-Takoradi Metropolitan Assembly'), ('Sunyani Municipal', 'Sunyani Municipal'), ('Sunyani Municipal Assembly', 'Sunyani Municipal Assembly'), ('Tano North Municipal', 'Tano North Municipal'), ('Tarkwa Nsuaem', 'Tarkwa Nsuaem'), ('Techiman', 'Techiman'), ('Techiman North', 'Techiman North'), ('Weija Gbawe', 'Weija Gbawe'), ('Wenchi', 'Wenchi'), ('Yeji Pru East', 'Yeji Pru East')], max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='management_unit_cost_centre',
            field=models.CharField(blank=True, choices=[('0101 ASL: Office Of The Admin Of Stool Lands', '0101 ASL: Office Of The Admin Of Stool Lands'), ('0101 MOC: Info. Services Dept. Head O COST CENTER', '0101 MOC: Info. Services Dept. Head O COST CENTER'), ('0613 ASL: ADMIN. OF STOOL LANDS, KUMASI', '0613 ASL: ADMIN. OF STOOL LANDS, KUMASI'), ('0408 ASL: Admin Of Stool Lands-Sekondi', '0408 ASL: Admin Of Stool Lands-Sekondi'), ('0712 ASL Admin Of Stool Lands Sunyani', '0712 ASL Admin Of Stool Lands Sunyani'), ('0313 ASL: Admin of stool lands Cape C Coast CENTRE', '0313 ASL: Admin of stool lands Cape C Coast CENTRE'), ('0600 REGIONAL ADMINI: ASHANTI REGIONAL', '0600 REGIONAL ADMINI: ASHANTI REGIONAL'), ('0208 ASL:ADMIN OF STOOL LANDS,KOFORIDUA COST CENTRE', '0208 ASL:ADMIN OF STOOL LANDS,KOFORIDUA COST CENTRE'), ('0101 OHCS: PROCUREMENT AND SUPPLY CHAIN COST CENTRE', '0101 OHCS: PROCUREMENT AND SUPPLY CHAIN COST CENTRE'), ('0408 LGS SEKONDI TAKORADI METRO. ASSEMBLY', '0408 LGS SEKONDI TAKORADI METRO. ASSEMBLY'), ('0101 CAGD/MT Stool Lands', '0101 CAGD/MT Stool Lands'), ('0101 ASL: Admin Of Stool Lands, Accra', '0101 ASL: Admin Of Stool Lands, Accra'), ('310 MOF/CAGD CENTRAL REGIONAL DIRECT', '310 MOF/CAGD CENTRAL REGIONAL DIRECT'), ('0200MOF/CAGD-Eastern Regional Directorate', '0200MOF/CAGD-Eastern Regional Directorate'), ('0600 MOF/CAGD: ASHANTIREGIONAL DIRECT.', '0600 MOF/CAGD: ASHANTIREGIONAL DIRECT.'), ('0813 ASL: Admin Of Stool Lands, TAccra Metropolitan Assemblyle', '0813 ASL: Admin Of Stool Lands, TAccra Metropolitan Assemblyle'), ('0400 MOF/CAGD WESTERN REGIONAL DIRECT', '0400 MOF/CAGD WESTERN REGIONAL DIRECT'), ('0313', '0313'), ('0800/LGS: NORTHERN REGIONAL COORDINATING COST CENTRE', '0800/LGS: NORTHERN REGIONAL COORDINATING COST CENTRE'), ('Administrator of Stool Lands -Western North Region', 'Administrator of Stool Lands -Western North Region'), ('0400 LGS WESTERN REGIONAL COORDINATING COUNCIL', '0400 LGS WESTERN REGIONAL COORDINATING COUNCIL'), ('0400MOF/CAGD:WESTERN REGIONAL DIRECT COST CENTRE', '0400MOF/CAGD:WESTERN REGIONAL DIRECT COST CENTRE'), ('MOF/CAGD: WESTERN REGIONAL DIRECTORATE', 'MOF/CAGD: WESTERN REGIONAL DIRECTORATE'), ('Office of of the Administrator of Stool Lands - Western North Region', 'Office of of the Administrator of Stool Lands - Western North Region'), ('OASL WESTERN NORTH', 'OASL WESTERN NORTH'), ('OASL.WESTERN NORTH REGION', 'OASL.WESTERN NORTH REGION'), ('Office of the Administrator of Stool Lands -Western North Region', 'Office of the Administrator of Stool Lands -Western North Region'), ('0313 Administrator of Stool Lands', '0313 Administrator of Stool Lands'), ('Adm. of Stool Lands, Kumasi Cost Centre', 'Adm. of Stool Lands, Kumasi Cost Centre'), ('310 MOF/CAGD UPPER DENKYIRA EAST MUNCIPAL', '310 MOF/CAGD UPPER DENKYIRA EAST MUNCIPAL'), ('1300 CAGD Ahafo regional Directorate COST CENTRE', '1300 CAGD Ahafo regional Directorate COST CENTRE'), ('OASL District Officers Conference - Ejisu', 'OASL District Officers Conference - Ejisu'), ('0101 MLF (OASL)', '0101 MLF (OASL)'), ('0313 ASL: Admin of stool lands, Cape coast center', '0313 ASL: Admin of stool lands, Cape coast center'), ('0101 PG: Parks And Gardens HQ', '0101 PG: Parks And Gardens HQ')], max_length=100, null=True),
        ),
    ]
