# Generated by Django 5.1 on 2025-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('Accra Metropolitan Assembly', 'Accra Metropolitan Assembly'), ('Head Office', 'Head Office'), ('Akim Oda', 'Akim Oda'), ('Regional Office', 'Regional Office'), ('Akim Ofoase', 'Akim Ofoase'), ('Akyemansa', 'Akyemansa'), ('Asamankese', 'Asamankese'), ('Asene Manso Akroso', 'Asene Manso Akroso'), ('Asunafo North', 'Asunafo North'), ('Asutifi North', 'Asutifi North'), ('Axim', 'Axim'), ('Begoro', 'Begoro'), ('Berekum', 'Berekum'), ('Birim North District', 'Birim North District'), ('Birim South District', 'Birim South District'), ('Bolgatanga Municipal', 'Bolgatanga Municipal'), ('Cape Coast', 'Cape Coast'), ('Daboase', 'Daboase'), ('Dormaa Municipal', 'Dormaa Municipal'), ('Dormaa West', 'Dormaa West'), ('Duayaw Nkwanta', 'Duayaw Nkwanta'), ('Ejisu', 'Ejisu'), ('Elubo', 'Elubo'), ('Enchi', 'Enchi'), ('Essikado', 'Essikado'), ('Kade District', 'Kade District'), ('Koforidua', 'Koforidua'), ('Kumasi Metropolitan Assembly', 'Kumasi Metropolitan Assembly'), ('Kumasi Metropolitan District', 'Kumasi Metropolitan District'), ('Kwahu Afram Plains South', 'Kwahu Afram Plains South'), ('Kwahu West', 'Kwahu West'), ('Kyebi', 'Kyebi'), ('La Dadekotopone', 'La Dadekotopone'), ('Mfantseman Municipal Assembly', 'Mfantseman Municipal Assembly'), ('New Juaben South Municipal', 'New Juaben South Municipal'), ('New Tafo-Akyem (Abuakwa North Municipal Assembly)', 'New Tafo-Akyem (Abuakwa North Municipal Assembly)'), ('Nkawkaw', 'Nkawkaw'), ('Nkoranza North & South', 'Nkoranza North & South'), ('Osu', 'Osu'), ('Sefwi Wiawso Municipal', 'Sefwi Wiawso Municipal'), ('Sekondi', 'Sekondi'), ('Sekondi-Takoradi Metropolitan Assembly', 'Sekondi-Takoradi Metropolitan Assembly'), ('Sunyani Municipal', 'Sunyani Municipal'), ('Sunyani Municipal Assembly', 'Sunyani Municipal Assembly'), ('Tano North Municipal', 'Tano North Municipal'), ('Tarkwa Nsuaem', 'Tarkwa Nsuaem'), ('Techiman', 'Techiman'), ('Techiman North', 'Techiman North'), ('Weija Gbawe', 'Weija Gbawe'), ('Wenchi', 'Wenchi'), ('Yeji Pru East', 'Yeji Pru East')], max_length=100, null=True, verbose_name='District'),
        ),
    ]
