# Generated by Django 5.1 on 2025-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('AHAFO', 'AHAFO'), ('ASHANTI', 'ASHANTI'), ('BONO & BONO EAST', 'BONO & BONO EAST'), ('CENTRAL', 'CENTRAL'), ('EASTERN', 'EASTERN'), ('GREATER ACCRA', 'GREATER ACCRA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('NORTHERN', 'NORTHERN'), ('UPPER EAST', 'UPPER EAST'), ('WESTERN', 'WESTERN'), ('Sefwi Wiawso', 'Sefwi Wiawso'), ('WESTERN NORTH', 'WESTERN NORTH')], max_length=20, null=True),
        ),
    ]
