# Generated by Django 5.1 on 2025-08-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_user_management_unit_cost_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='directorate',
            field=models.CharField(blank=True, choices=[('Administration & Human Resource Directorate - ICT Unit', 'Administration & Human Resource Directorate - ICT Unit'), ('Administration & Human Resource Directorate - Information Unit & Public Relations Unit', 'Administration & Human Resource Directorate - Information Unit & Public Relations Unit'), ('Administration & Human Resource Directorate - Procurement Unit', 'Administration & Human Resource Directorate - Procurement Unit'), ('Administration & Human Resource Directorate - Records', 'Administration & Human Resource Directorate - Records'), ('Administration & Human Resource Directorate - Transport Unit', 'Administration & Human Resource Directorate - Transport Unit'), ('Audit Unit', 'Audit Unit'), ('Finance Directorate', 'Finance Directorate'), ('General Administration & Human Resource Directorate', 'General Administration & Human Resource Directorate'), ('Land Administration Directorate', 'Land Administration Directorate'), ('Legal Unit', 'Legal Unit'), ('Admin Directorate', 'Admin Directorate'), ('Operations Directorate', 'Operations Directorate'), ('Policy Planning Directorate', 'Policy Planning Directorate'), ('Research Statistics & Information Management Directorate', 'Research Statistics & Information Management Directorate')], max_length=100, null=True),
        ),
    ]
