# Generated by Django 5.1 on 2025-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_user_directorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('Accounts Class', 'Accounts Class'), ('Administrative Class', 'Administrative Class'), ('Audit Class', 'Audit Class'), ('General', 'General'), ('Drivers Class', 'Drivers Class'), ('Executive Class', 'Executive Class'), ('Information Class', 'Information Class'), ('Information Technology Class', 'Information Technology Class'), ('Labourers Class', 'Labourers Class'), ('Procurement Class', 'Procurement Class'), ('Programme Class', 'Programme Class'), ('Records Class', 'Records Class'), ('Revenue Class', 'Revenue Class'), ('Revenue Inspector Class', 'Revenue Inspector Class'), ('Sanitation Class', 'Sanitation Class'), ('Secretarial Class', 'Secretarial Class'), ('Security Class', 'Security Class'), ('Stool Lands Class', 'Stool Lands Class'), ('Stool Lands Inspectors Class', 'Stool Lands Inspectors Class'), ('Stool Lands Revenue Class', 'Stool Lands Revenue Class')], max_length=100, null=True, verbose_name='class'),
        ),
    ]
