# Generated by Django 5.1 on 2025-08-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_user_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='on_leave_type',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('STUDY LEAVE WITH PAY', 'STUDY LEAVE WITH PAY'), ('STUDY LEAVE WITHOUT PAY', 'STUDY LEAVE WITHOUT PAY')], max_length=50, null=True),
        ),
    ]
