# Generated by Django 5.1 on 2025-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_user_on_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fulltime_contract_staff',
            field=models.CharField(blank=True, choices=[('Fulltime', 'Fulltime'), ('CONTRACT', 'CONTRACT')], max_length=20, null=True),
        ),
    ]
