# Generated by Django 5.1 on 2025-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_alter_user_fulltime_contract_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fulltime_contract_staff',
            field=models.CharField(blank=True, choices=[('FULLTIME', 'FULLTIME'), ('CONTRACT', 'CONTRACT')], max_length=20, null=True),
        ),
    ]
