# Generated by Django 5.1 on 2025-08-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_grade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Current Grade',
                'verbose_name_plural': 'Current Grades',
            },
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
