# Generated by Django 5.1 on 2025-08-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_currentgrade_alter_classes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_unit_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Management Unit',
                'verbose_name_plural': 'Management Units',
            },
        ),
    ]
