# Generated by Django 5.1 on 2025-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_districts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOfGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Change of Grade',
                'verbose_name_plural': 'Change of Grades',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
