# Generated by Django 5.1 on 2025-08-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_changeofgrade_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department', verbose_name='Directorate'),
        ),
    ]
