# Generated by Django 5.1 on 2025-08-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_user_directorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorates', to='account.department', verbose_name='Directorate'),
        ),
    ]
