# Generated by Django 5.1 on 2025-08-14 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_user_directorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='account.classes', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='change_of_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_of_gradee', to='account.changeofgrade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_gradee', to='account.currentgrade', verbose_name='current grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='account.districts', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='management_unit_cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_unitt', to='account.managementunit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_gradee', to='account.currentgrade', verbose_name='next grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='account.region', verbose_name='Region'),
        ),
    ]
