# Generated by Django 5.1 on 2025-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_user_category_alter_user_change_of_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional',
            field=models.CharField(blank=True, choices=[('PROFESSIONAL', 'PROFESSIONAL'), ('SUB PROFESSIONAL', 'SUB PROFESSIONAL')], max_length=50, null=True),
        ),
    ]
