# Generated by Django 5.1 on 2025-08-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_user_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fulltime_contract_staff',
            field=models.CharField(blank=True, choices=[('FULLTIME', 'FULLTIME'), ('CONTRACT', 'CONTRACT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
