# Generated by Django 5.1 on 2025-08-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_user_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_health_insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
