# Generated by Django 5.1 on 2025-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_alter_user_national_health_insurance_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
