# Generated by Django 5.1 on 2025-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_alter_user_social_security_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
