# Generated by Django 5.1 on 2025-08-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_health_insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
