# Generated by Django 5.1 on 2025-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_alter_user_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professional',
            field=models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Subprofessional', 'Subprofessional')], max_length=50, null=True),
        ),
    ]
