# Generated by Django 5.1 on 2025-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_alter_user_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classes_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
