# Generated by Django 5.1 on 2025-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_alter_classes_classes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentgrade',
            name='current_grade',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
