# Generated by Django 5.1 on 2025-09-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_alter_currentgrade_current_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
