# Generated by Django 5.1 on 2025-09-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_retirement',
        ),
    ]
