# Generated by Django 5.1 on 2025-09-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_remove_user_date_of_retirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
