# Generated by Django 5.1 on 2025-09-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_user_profile_picture_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_salary_level',
            field=models.CharField(blank=True, choices=[('SS.5', 'SS.5'), ('SS.6', 'SS.6'), ('SS.7', 'SS.7'), ('SS.8', 'SS.8'), ('SS.9', 'SS.9'), ('SS.10', 'SS.10'), ('SS.11', 'SS.11'), ('SS.12', 'SS.12'), ('SS.13', 'SS.13'), ('SS.14', 'SS.14'), ('SS.15', 'SS.15'), ('SS.16', 'SS.16'), ('SS.17', 'SS.17'), ('SS.18', 'SS.18'), ('SS.19', 'SS.19'), ('SS.20', 'SS.20'), ('SS.21', 'SS.21'), ('SS.22', 'SS.22'), ('SS.23', 'SS.23'), ('SS.24', 'SS.24'), ('SS.25', 'SS.25')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_salary_level',
            field=models.CharField(blank=True, choices=[('SS.5', 'SS.5'), ('SS.6', 'SS.6'), ('SS.7', 'SS.7'), ('SS.8', 'SS.8'), ('SS.9', 'SS.9'), ('SS.10', 'SS.10'), ('SS.11', 'SS.11'), ('SS.12', 'SS.12'), ('SS.13', 'SS.13'), ('SS.14', 'SS.14'), ('SS.15', 'SS.15'), ('SS.16', 'SS.16'), ('SS.17', 'SS.17'), ('SS.18', 'SS.18'), ('SS.19', 'SS.19'), ('SS.20', 'SS.20'), ('SS.21', 'SS.21'), ('SS.22', 'SS.22'), ('SS.23', 'SS.23'), ('SS.24', 'SS.24'), ('SS.25', 'SS.25')], max_length=20, null=True),
        ),
    ]
