# Generated by Django 5.1 on 2025-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_alter_user_current_salary_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('POINT 1', 'POINT 1'), ('POINT 2', 'POINT 2'), ('POINT 3', 'POINT 3'), ('POINT 4', 'POINT 4'), ('POINT 5', 'POINT 5'), ('POINT 6', 'POINT 6'), ('POINT 7', 'POINT 7'), ('POINT 8', 'POINT 8'), ('POINT 9', 'POINT 9'), ('POINT 10', 'POINT 10'), ('POINT 11', 'POINT 11'), ('POINT 12', 'POINT 12'), ('POINT 13', 'POINT 13'), ('POINT 14', 'POINT 14'), ('POINT 15', 'POINT 15')], max_length=20, null=True),
        ),
    ]
