# Generated by Django 5.1 on 2025-09-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_alter_user_current_salary_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Esq.', 'Esq.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr..', 'Dr.')], max_length=20, null=True),
        ),
    ]
