# Generated by Django 5.1 on 2025-09-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_alter_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_of_years_in_service',
        ),
        migrations.RemoveField(
            model_name='user',
            name='years_on_current_grade',
        ),
    ]
