# Generated by Django 5.1 on 2025-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_remove_user_number_of_years_in_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_qualification',
            field=models.CharField(blank=True, choices=[('ACCA LEVEL 1', 'Acca Level 1'), ('ADVANCE AND ORDINARY LEVEL CERTIFICATE', 'Advance And Ordinary Level Certificate'), ('ADVANCE BUSINESS CERTIFICATE', 'Advance Business Certificate'), ('ADVANCE BUSINESS CERTIFICATE EXAMINATION', 'Advance Business Certificate Examination'), ('ADVANCE LEVEL', 'Advance Level'), ('ADVANCE LEVEL CERTIFICATE', 'Advance Level Certificate'), ('BTECH', 'Btech'), ('CERTIFICATE IN PHILOSOPHY', 'Certificate In Philosophy'), ('CERTIFICATE IN SURVEY & MAPPING', 'Certificate In Survey & Mapping'), ('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma'), ('DIPLOMA IN BUSINESS STUDIES', 'Diploma In Business Studies'), ('DIPLOMA IN BUSINESS STUDIES (ACCOUNTING OPTION)', 'Diploma In Business Studies (Accounting Option)'), ('DRIVER MECHANIC CERTIFICATE', 'Driver Mechanic Certificate'), ('GCE ADVANCE LEVEL', 'Gce Advance Level'), ('GCE ORDINARY & ADVANCE LEVEL', 'Gce Ordinary & Advance Level'), ('GCE ORDINARY LEVEL', 'Gce Ordinary Level'), ('GOVERNMENT SECRETARY CERTIFICATE', 'Government Secretary Certificate'), ('HND', 'Hnd'), ('ICAG', 'Icag'), ('JHS', 'Jhs'), ('MASTERS', 'Masters'), ('MIDDLE SCHOOL LEAVING CERTIFICATE', 'Middle School Leaving Certificate'), ('MOTOR VEHICLE MECHANIC WORK', 'Motor Vehicle Mechanic Work'), ('MSLC', 'Mslc'), ('NAPTEX CERTIFICATE II INTERMIDIATE', 'Naptex Certificate Ii Intermidiate'), ('NONE', 'None'), ('RSA STAGE 3', 'Rsa Stage 3'), ('SECRETARIALSHIP', 'Secretarialship'), ('SSCE/WASSCE', 'Ssce/Wassce'), ('STENOGRAPHER SECRETARY CERTIFICATE', 'Stenographer Secretary Certificate')], max_length=100, null=True),
        ),
    ]
