# Generated by Django 5.1 on 2025-09-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_alter_user_academic_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
