# Generated by Django 5.1 on 2025-09-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_academicqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='academic_qualification',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_qualifications',
            field=models.ManyToManyField(blank=True, to='account.academicqualification'),
        ),
    ]
