# Generated by Django 5.1 on 2025-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_remove_user_academic_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_grade', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Next Grade',
                'verbose_name_plural': 'Next Grades',
            },
        ),
    ]
