# Generated by Django 5.1 on 2025-09-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_alter_user_next_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='next_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_gradeea', to='account.nextgrade', verbose_name='next grade'),
        ),
    ]
