# Generated by Django 5.1 on 2025-09-13 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_alter_user_next_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRemovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
