# Generated by Django 5.1 on 2025-09-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_userremovallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='at_post_on_leave',
            field=models.CharField(blank=True, choices=[('AT POST', 'AT POST'), ('ON LEAVE', 'ON LEAVE')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_salary_level',
            field=models.CharField(blank=True, choices=[('SS.5', 'SS.5'), ('SS.6', 'SS.6'), ('SS.7', 'SS.7'), ('SS.8', 'SS.8'), ('SS.9', 'SS.9'), ('SS.10', 'SS.10'), ('SS.11', 'SS.11'), ('SS.12', 'SS.12'), ('SS.13', 'SS.13'), ('SS.14', 'SS.14'), ('SS.15', 'SS.15'), ('SS.16', 'SS.16'), ('SS.17', 'SS.17'), ('SS.18', 'SS.18'), ('SS.19', 'SS.19'), ('SS.20', 'SS.20'), ('SS.21', 'SS.21'), ('SS.22', 'SS.22'), ('SS.23', 'SS.23'), ('SS.24', 'SS.24'), ('SS.25', 'SS.25')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_salary_point',
            field=models.CharField(blank=True, choices=[('POINT 1', 'POINT 1'), ('POINT 2', 'POINT 2'), ('POINT 3', 'POINT 3'), ('POINT 4', 'POINT 4'), ('POINT 5', 'POINT 5'), ('POINT 6', 'POINT 6'), ('POINT 7', 'POINT 7'), ('POINT 8', 'POINT 8'), ('POINT 9', 'POINT 9'), ('POINT 10', 'POINT 10'), ('POINT 11', 'POINT 11'), ('POINT 12', 'POINT 12'), ('POINT 13', 'POINT 13'), ('POINT 14', 'POINT 14'), ('POINT 15', 'POINT 15')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=222, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_health_insurance_number',
            field=models.CharField(blank=True, max_length=222, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_salary_level',
            field=models.CharField(blank=True, choices=[('SS.5', 'SS.5'), ('SS.6', 'SS.6'), ('SS.7', 'SS.7'), ('SS.8', 'SS.8'), ('SS.9', 'SS.9'), ('SS.10', 'SS.10'), ('SS.11', 'SS.11'), ('SS.12', 'SS.12'), ('SS.13', 'SS.13'), ('SS.14', 'SS.14'), ('SS.15', 'SS.15'), ('SS.16', 'SS.16'), ('SS.17', 'SS.17'), ('SS.18', 'SS.18'), ('SS.19', 'SS.19'), ('SS.20', 'SS.20'), ('SS.21', 'SS.21'), ('SS.22', 'SS.22'), ('SS.23', 'SS.23'), ('SS.24', 'SS.24'), ('SS.25', 'SS.25')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=222, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=222, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_category',
            field=models.CharField(blank=True, choices=[('SENIOR STAFF', 'SENIOR STAFF'), ('JUNIOR STAFF', 'JUNIOR STAFF')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('Esq.', 'Esq.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr..', 'Dr.')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=222, null=True, unique=True),
        ),
    ]
