# Generated by Django 5.1 on 2025-09-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_alter_user_at_post_on_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accommodation_status',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'PERSONAL'), ('RENTED', 'RENTED'), ('OFFICIAL RESIDENCE - OASL', 'OFFICIAL RESIDENCE - OASL'), ('OFFICIAL RESIDENCE - OASL', 'OFFICIAL RESIDENCE - OASL'), ('OFFICIAL RESIDENCE - GoG', 'OFFICIAL RESIDENCE - GoG'), ('OFFICIAL RESIDENCE - GoG', 'OFFICIAL RESIDENCE - GoG')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=222, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='on_leave_type',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('STUDY LEAVE WITH PAY', 'STUDY LEAVE WITH PAY'), ('STUDY LEAVE WITHOUT PAY', 'STUDY LEAVE WITHOUT PAY')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='payroll_status',
            field=models.CharField(blank=True, choices=[('ACTIVE (PAID)', 'ACTIVE (PAID)'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional',
            field=models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Subprofessional', 'Subprofessional')], max_length=222, null=True),
        ),
    ]
