# Generated by Django 5.1 on 2025-09-13 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('AHAFO', 'AHAFO'), ('ASHANTI', 'ASHANTI'), ('BONO & BONO EAST', 'BONO & BONO EAST'), ('CENTRAL', 'CENTRAL'), ('EASTERN', 'EASTERN'), ('GREATER ACCRA', 'GREATER ACCRA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('NORTHERN', 'NORTHERN'), ('UPPER EAST', 'UPPER EAST'), ('WESTERN', 'WESTERN'), ('Greater Accra', 'Greater Accra'), ('WESTERN NORTH', 'WESTERN NORTH')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
